name = "packwizz"
author = "oakbricks"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30efc034522cef2142f2e3ac4ae4ca0d84b81a2fdc58dcf37a1295af5a7b7ff0"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
