name = "packwizz"
author = "oakbricks"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d995ae4c0a11a8944658c1acaf1a6c89f14f0ef3fffd9b3ba050964c569cc46"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
