name = "Cull Leaves"
filename = "cullleaves-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3342/334/cullleaves-2.2.0.jar"
hash-format = "murmur2"
hash = "1428146386"

[update]
[update.curseforge]
file-id = 3342334
project-id = 423254
release-channel = "beta"
