name = "Physics Mod"
filename = "physics-mod-2.5.8-mc-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3460/160/physics-mod-2.5.8-mc-1.17.1.jar"
hash-format = "murmur2"
hash = "467968511"

[update]
[update.curseforge]
file-id = 3460160
project-id = 442735
release-channel = "beta"
