name = "Physics Mod"
filename = "physics-mod-2.5.5-mc-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3437/944/physics-mod-2.5.5-mc-1.17.1.jar"
hash-format = "murmur2"
hash = "1694715095"

[update]
[update.curseforge]
file-id = 3437944
project-id = 442735
release-channel = "beta"
